djangoCupboardTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from foodTracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ='index'),
    path('foodtracker/', include('foodTracker.urls'))
]

foodTracker/urls.py
from django.template.defaulttags import url
from django.urls import path

from foodTracker import views

app_name = 'foodTracker'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('index', views.index, name='index'),
    path('addFood', views.addFood, name ='addFood'),
    path('deleteFood/<str:id>', views.deleteFood, name='deleteFood'),
]

foodTracker/models.py
from django.db import models


FOOD_TYPE_CHOICES = {
    "Canned": "Canned",
    "Packet": "Packet",
    "Meat": "Meat",
    "Frozen Meal": "Frozen Meal",
    "Sauce":"Sauce",
    "Pasta":"Pasta",
    "Drink Mix":"Drink Mix",
    "Cereal": "Cereal",
    "Cheese": "Cheese",
    "Lunch Meat": "Lunch Meat",
    "Drink": "Drink",




}
# Create your models here.
class FoodItem(models.Model):
  name = models.CharField(max_length=255)
  food_type = models.CharField(max_length=255, choices=FOOD_TYPE_CHOICES, default="Canned")
  amount_on_hand = models.DecimalField(max_digits=5, decimal_places=2)

  def __str__(self):
      return self.name

foodTracker/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from foodTracker.models import FoodItem
from django.template import loader
# Create your views here.


def index(request):
    data = FoodItem.objects.all().values()
    template = loader.get_template('index.html')
    context = {'data': data}

    return HttpResponse(template.render(context, request))

def addFood(request):

    food, created = FoodItem.objects.update_or_create(
    name="Colby Cheese Slices",
    food_type="Cheese",
    amount_on_hand=16,
    )
    return redirect('index')
    #return render(request, 'addFood.html', )


def deleteFood(request,id =None):
    item = get_object_or_404(FoodItem, id=id)
    item.delete()
    return redirect('index')

templates/addFood.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Food Item</title>
</head>
<body>
Let's add a food item
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
        <title>My Table</title>
        <style>
            table {
                width: 75%;
                border-collapse: separate;
            }
            th, td {
                padding: 8px;
                text-align: left;
                border: 1px solid #ddd;
            }
            th {
                background-color: #f2f2f2;
            }
        </style>
    </head>
<head>
<title>Food Tracker Home</title>
</head>
<body>
<h1>Vash's food Tracker</h1>
<div>
 <p> This is a simple program to keep track of what's in the pantry for ease of grocery Shopping.
 <br /> sure there are other programs out there but hey this gets me back in the swing of Django</p>
</div>
<table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Food Type</th>
                <th>Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.food_type }}</td>
                <td>{{ item.amount_on_hand }}</td>
                <td>
                    <form method="post" action="{% url 'foodTracker:deleteFood' item.id %}">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
<div>
<a href="index">Home</a><br />
</div>
</body>
</html>